[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@interfaces=src/interfaces",
    "@openzeppelin=lib/openzeppelin-contracts/contracts",
    "@chainlink=lib/chainlink-brownie-contracts",
    "@solmate=lib/solmate/src",
    "@foundry-devops/=lib/foundry-devops/src"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }

